### ISSUE TITLE
Fails due to execution policy other than "Restricted" or "Unrestricted"

### ISSUE THREAD

**Issue by Coalbus** [mbarr564/New-SubredditHTMLArchive#1]
The script checks for an execution policy of "Restricted" and changes it to "Unrestricted" if found. But there are other execution policies (such as "RemoteSigned", "AllSigned", "Bypass") that would not be caught by this check. If the machine's execution policy is set to one of these other policies, the script will fail as it did in my case. The check should ideally be for anything that _isn't_ "Unrestricted".

**Comment by mbarr564** [comment]
You're correct -- When I was writing the batch script, my thought was that, anyone that knows about the other execution policies, isn't going to be using the easy install script. However, I just added a workaround to the main PowerShell script, for some old nemesis post IDs that keep generating filesystem syntax errors, so I'm going to release that as 2.2.2, probably tomorrow, and include an updated batch script too. Thanks for your feedback.

**Comment by mbarr564** [comment]
Closing as fixed in the 2.2.2 release:
https://github.com/mbarr564/New-SubredditHTMLArchive/releases/tag/2.2.2

Sorry for my delay, I got sidetracked on rebuilding my 3D printer over the last few days.
